### PR TITLE
Updating trace viewer

### PR DESCRIPTION
**Pull request by vibaldem**
+ Changing how data is loaded by using getgzip instead of file_get_contents

### CODE REVIEW

**Comment by pmeenan** [comment]
Awesome, thanks.

**Comment by wildlyinaccurate** [comment]
The trace viewer no longer works. I wonder if it's related to this PR?

```
ReferenceError: tr is not defined
trace.php:3701:99
ReferenceError: Polymer is not definedtrace.php:10513:5
```

**Comment by pmeenan** [comment]
I'll see if I can find the details but you need to register an origin trial
that keeps polymer working in chrome 80+ until they rewrite the trace
viewer. There is a setting in settings.ini where you can put the origin
trial key.

**Comment by pmeenan** [comment]
Origin trial is here:
https://developers.chrome.com/origintrials/#/view_trial/2431943798780067841

The setting is trace_viewer_token:
https://github.com/WPO-Foundation/webpagetest/blob/master/www/chrome/trace.php

**Comment by wildlyinaccurate** [comment]
Thanks Pat! Got it working now :)

**Pull request merged**
