### PR TITLE
Create .dockerignore

### PR DESCRIPTION
**Pull request by jangrewe**
Don't send the `.git` folder to the Docker context when building the image, which saves (currently) 627MB during the build.

### CODE REVIEW

**Comment by sburnicki** [comment]
Good point. Actually the file could also look like
```
*
!Dockerfile
!www
```
Since we only need the www folder (don't know about the Dockerfile itself). This effectively reduces the build context to 56MB :)

**Comment by jangrewe** [comment]
The Dockerfile is ignored automatically, IIRC, but `www` is actually required - else you'd have no content to display!

**Comment by sburnicki** [comment]
Okay, then it could come down to
```
*
!www
```
which means: Exclude everything but the `www` folder (see https://docs.docker.com/engine/reference/builder/#/dockerignore-file)

**Comment by jangrewe** [comment]
Well, you'd also have to exclude the `docker` folder, because that is also partially copied. I think we're fine by at least excluding `.git` withouth breaking anything.

**Comment by sburnicki** [comment]
Okay ;)

**Pull request merged**
