### PR TITLE
Fix Chrome viewport sizing by loading an empty document before attemp…

### PR DESCRIPTION
**Pull request by david-poirier-csn**
…ting resize

Fix Firefox viewport sizing by forcing viewport re-measurement inside UpdateBrowserWindow method
Fix off-by-one errors inside viewport measurement

#630

### CODE REVIEW

**Comment by zeman** [comment]
Does this fix the viewport sizing issues we're seeing here https://github.com/WPO-Foundation/webpagetest/issues/630

**Comment by david-poirier-csn** [comment]
I reckon it should. The issues are probably caused by newer versions of Chrome creating child processes in a different way, but that's just a guess. The fix makes sure the window is open before attempting a resize, which "works on my machine" :)

Testing would be appreciated. You'd need to replace your "wptdriver.exe" and "wpthook.dll" files with ones built from my fork. If you need binaries let me know and I'll put them in dropbox for you.

**Comment by pmeenan** [comment]
No need for a custom build.  Looks simple enough and other that curiosity why it is being done after the second blank page instead of the first, should be low risk.  I just pushed wptdriver 280 to prod with the fix.

@david-poirier-csn - huge thanks for looking into it and the fix.

**Comment by david-poirier-csn** [comment]
No worries! 
I changed it to resize on the second load because when using Chrome it was trying to resize before the window was created, and the resize code will not try to operate on the same window twice. I could have changed that, but it seems simpler to load a blank page and do a no-op.

**Pull request merged**
