### PR TITLE
Update sign up page with new designs for price selection.

### PR DESCRIPTION
**Pull request by deathbearbrown**
Screen Shot 2022-07-26 at 12 48 31 PM
Screen Shot 2022-07-26 at 12 48 22 PM

This closes 
https://github.com/WPO-Foundation/webpagetest/issues/2119

One thing I cannot figure out is setting `$tab` globally in order to get the nav highlighted. I set it in signup-flow-step-1.php before the require_once of the header.inc, which is what checks for tab and sets it to string (tab is later used in wpt-header.php) but... it doesn't add to the global space....

### CODE REVIEW

**Comment by stoyan** [comment]
Nit: possible to update the page title? Maybe it's just for power users but I have too many "WebPageTest" tabs :)

**Comment by stoyan** [comment]
Nit: overlap in some screen sizes
Screen Shot 2022-07-26 at 4 24 37 PM

**Comment by scottjehl** [comment]
This looks GREAT!

A couple very small things I noticed before it's ready to go: 
- At tablet-ish breakpoints, the top text gets crashy with black text over the purple. I think those breakpoints could have a good amount of margin under the purple header to give the text some space over the white. 
image
- The WPT pro logo and text can swap out for this in an image element for alignment and consistency /images/wpt-logo-pro.svg 
image
- minor thing, but for units, I've been trying to shift text a touch smaller, and the weight to normal or light for more texture. That impacts a couple places on this page: 
image and 
image
- These x icons can be more consistent with the green checks by using this SVG: https://user-images.githubusercontent.com/214783/181105702-3c58def5-332d-4a7f-bb82-68b899750c4d.svg

**Comment by scottjehl** [comment]
> Nit: possible to update the page title? Maybe it's just for power users but I have too many "WebPageTest" tabs :)

I think that'd be a good global issue to look at yeah?

**Comment by scottjehl** [comment]
A couple more weird ones.

- On iOS, the yellow buttons have white text for me. Maybe iOS needs a reset on button text or appearance?
- Also on iOS, the page breaks out horizontally. It looks like the button flex layout needs to wrap for the contact us box, and maybe the buttons up top need some slightly smaller font size, padding, margin?

**Comment by deathbearbrown** [comment]
- [ ] more breakpoints for header overlap
- [ ] change to WPT pro logo
- [ ] switch bold font-weight to normal or lighter for buttons and callouts
- [ ] update the X circle icon
- [ ] iOS buttons are white text
- [ ] iOS breaks weird around the contact us page?
- [ ] add a new title (temporarily for this page just update it)

**Comment by deathbearbrown** [comment]
I think I fixed the header overlap thing yesterday and must have not made a note of it cause I can't recreate it now. :/

**Review by scottjehl — APPROVED** [review]
Great stuff. Thanks!

**Pull request merged**
