### PR TITLE
Cursor: pointer for account verification resend link

### PR DESCRIPTION
**Pull request by stoyan**
this one:
Screen Shot 2022-07-13 at 1 43 59 PM

### CODE REVIEW

**Comment by deathbearbrown** [comment]
ok did you get a prettier extension for vscode? should we add linting as part of on commit... how should we do this

**Comment by stoyan** [comment]
Prettier VSCode https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
Prettier vim https://prettier.io/docs/en/vim.html
We should probably add linting too, but no idea atm

**Comment by stoyan** [comment]
Stylelint for CSS linting (vim and VSCode)
https://stylelint.io/user-guide/integrations/editor/

**Comment by stoyan** [comment]
moved to only the code change #2172 sans prettier

**Pull request closed without merging**
