### PR TITLE
Add GoCache as a known CDN

### PR DESCRIPTION
**Pull request by gocachebr**
GoCache is a next-gen CDN platform to speed up and protect any website in a smart in simple way.

### CODE REVIEW

**Comment by pmeenan** [comment]
Do you have an example site running on GoCache or a network map of some kind showing POPs? I just need to check to make sure it isn't just offloading static files to separate hosting and actually distributes content to various locations and serves from the location closest to the user (the primary reason for WPT's CDN detection).

**Comment by gocachebr** [comment]
You can take a look at the website www.papodehomem.com.br. They are our
customers.

On Mon, Oct 5, 2015 at 2:16 PM, Patrick Meenan <notifications@github.com>
wrote:

> Do you have an example site running on GoCache or a network map of some
> kind showing POPs? I just need to check to make sure it isn't just
> offloading static files to separate hosting and actually distributes
> content to various locations and serves from the location closest to the
> user (the primary reason for WPT's CDN detection).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPO-Foundation/webpagetest/pull/498#issuecomment-145602664>
> .
>



-- 

<http://www.gocache.com.br>

Guilherme Eberhart
guilherme@gocache.com.br / +55 11 99520-3500

GoCache
http://www.gocache.com.br

[image: Facebook] <https://www.facebook.com/gocache> [image: Twitter]
<https://www.twitter.com/gocachebr> [image: Linkedin]
<https://www.linkedin.com/company/gocache> [image: skype]

**Comment by pmeenan** [comment]
Looks like they are using Cloudfront (at least based on a test I just ran: http://www.webpagetest.org/result/151208_DC_c0521bdf35e60c50669e42a740961bc7/1/performance_optimization/#use_of_cdn ).  Any others?

**Comment by gocachebr** [comment]
They are originally using CloudFront, but GoCache is in front of their
assets in AWS. If you make a dns lookup from several locations, you'll see
that the content is distributed by our network.

https://www.whatsmydns.net/#A/www.papodehomem.com.br
https://www.whatsmydns.net/#A/assets.papodehomem.com.br

Additionaly in all requests you'll see this header:

Server: gocache


Another customer is lopes.com.br, that is using GoCache to deliver static
content in internal pages:

Website: www.lopes.com.br/imoveis/SP/sao-paulo
Static host: multimidia.lopes.com.br
https://www.whatsmydns.net/#A/multimidia.lopes.com.br

On Tue, Dec 8, 2015 at 12:19 PM, Patrick Meenan <notifications@github.com>
wrote:

> Looks like they are using Cloudfront (at least based on a test I just ran:
> http://www.webpagetest.org/result/151208_DC_c0521bdf35e60c50669e42a740961bc7/1/performance_optimization/#use_of_cdn
> ). Any others?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPO-Foundation/webpagetest/pull/498#issuecomment-162894199>
> .
>



-- 

<http://www.gocache.com.br>

Guilherme Eberhart
guilherme@gocache.com.br / +55 11 99520-3500

GoCache
http://www.gocache.com.br

[image: Facebook] <https://www.facebook.com/gocache> [image: Twitter]
<https://www.twitter.com/gocachebr> [image: Linkedin]
<https://www.linkedin.com/company/gocache> [image: skype]

**Pull request closed without merging**
