### PR TITLE
link css page

### PR DESCRIPTION
**Pull request by jirawat050**
untitled

### CODE REVIEW

**Comment by pmeenan** [comment]
It is already included by head.inc: https://github.com/WPO-Foundation/webpagetest/blob/master/www/head.inc#L26

**Comment by jirawat050** [comment]
@pmeenan   but not show css if dont't edit to
#  echo "<link rel=\"stylesheet\" href=\"{$GLOBALS['cdnPath']}pagestyle.css?v=" . VER_CSS . "\" type=\"text/css\">\n";

**Comment by jirawat050** [comment]
if i edit is echo "<link rel="stylesheet" href="{$GLOBALS['cdnPath']}pagestyle.css?v=" . VER_CSS . "" type="text/css">\n"; ?

**Comment by jirawat050** [comment]
before <li class="traceroute"><a href="/traceroute.php">Traceroute</a></li> not show
but edit <li class="traceroute"><a href="traceroute.php">Traceroute</a></li> show

**Comment by jirawat050** [comment]
before a href="traceroute.php">Traceroute</a> show link
but <li class="traceroute"><a href="/traceroute.php">Traceroute</a</li> not show

**Comment by pmeenan** [comment]
Are you running a php server locally?  If so, check the error logs and see why it is failing.  Something else is broken if the head.inc code isn't loading it correctly.

**Comment by jirawat050** [comment]
i can edit code and new PR if i edit correct

**Comment by pmeenan** [comment]
The code works everywhere else it is running so there is something about your local setup or code that isn't working.  Changing the code is not the correct fix.  You need to debug your local installation to see why it isn't working.

**Pull request closed without merging**
