### PR TITLE
Resolve IPs and test to make sure they are not in a reserved range

### PR DESCRIPTION
**Pull request by kjoconnor**
I haven't written PHP in a very long time so let me know if this doesn't match any style guidelines. I just tried to match the functions around it.

I had emailed you about this privately and you ended up adding the link local checks about a month ago (thanks!), I think this just makes doubly sure that we wouldn't be requesting strange pages.

### CODE REVIEW

**Comment by pmeenan** [comment]
Only change I'd suggest is to only go the gethostbyname if private IP testing is disabled.

That said, it would probably be better to pass a flag down to the test agents that indicates private testing is not allowed and have them fail the connections like we do for the link-local addresses.  Otherwise there are WAY too many ways around it (test a page that redirects to a private IP, test a page with an iFrame to the private IP, etc).

**Comment by kjoconnor** [comment]
Do you know whereabouts in the code that flag could be passed? Or would that require a major rearchitecting?

**Comment by pmeenan** [comment]
The flag itself would be passed in runtest.php when the task is built -
https://github.com/WPO-Foundation/webpagetest/blob/master/www/runtest.php#L1806
(probably something like "blockprivate=1").

Then in wptdriver where the connections are hooked we'd check the flag and
if the IP was a private IP like we check link local:
https://github.com/WPO-Foundation/webpagetest/blob/master/agent/wpthook/track_sockets.cc#L117

Same in urlblast -
https://github.com/WPO-Foundation/webpagetest/blob/master/agent/browser/ie/pagetest/WsHook.cpp#L264

Most of the work would probably be in plumbing the setting through from the
task into the parts of the code that do the blocking.

**Comment by pmeenan** [comment]
Closing from lack of activity.  Please re-open if you take another run at it.

**Pull request closed without merging**
