### PR TITLE
Add function Download Filepdf for show result customwaterfall.php

### PR DESCRIPTION
**Pull request by pao0012**

### CODE REVIEW

**Comment by jirawat050** [comment]
@pmeenan It correct?

**Comment by pmeenan** [comment]
Do you have examples of what the output reports look like?  Grabbing an image of the current page and embedding it in a PDF doesn't seem like a strictly better result than just printing the current page to a PDF.

IF we go down this path (and it's a strong IF at this point) I'd also want the js libs to only be fetched when actually exporting.  Having to download and parse then for every visit for the few cases where someone will export a PDF is not worth the performance hit.

What I'd really expect from a proper PDF report looks more like:
- Generate an executive HTML report that includes all of the performance data, optimization suggestions (with thumbnails of the images), etc.
- Have an option to generate the same report as a PDF.
- The PDF would not be one massive image.  The text would all be text, etc.
- The PDF export could be a print-friendly stylesheet that can be used with a browser's native print to PDF support

**Comment by pao0012** [comment]
Do yo need text pdf ?not image

**Comment by pao0012** [comment]
i think sometime host not  english language which not support UTf8.I think to image

**Comment by pao0012** [comment]
I edit not full page but to is screenshort. Sorry I edit not problem

**Comment by pao0012** [comment]
i add function print .Sorry if you need

**Comment by pmeenan** [comment]
Instead of submitting code for PDF exporting of current pages, please propose a design and implementation on the [existing PDF report issue](https://github.com/WPO-Foundation/webpagetest/issues/14).  Code shouldn't be written until we can agree on what PDF support should look like and how it should work.

**Pull request closed without merging**
