### PR TITLE
Fixed to Delete input video/index

### PR DESCRIPTION
**Pull request by DQIJAO**

### CODE REVIEW

**Comment by pmeenan** [comment]
Why does it need an alert box in this case?  If you have a failcase where there are URLs in the list that can't be deleted it is likely a different bug.  Otherwise trying to delete an empty list should never happen.

**Comment by DQIJAO** [comment]
I think it alert if nothing left input in enter data
screen shot 2017-12-13 at 9 13 40 pm

**Comment by pmeenan** [comment]
That case would be better to just hide the remove link when there is only one input.  An alert box is pretty jarring and not very user-friendly.

**Comment by DQIJAO** [comment]
So i should edit file video/index?

**Comment by pmeenan** [comment]
Only if you know what you are doing and have a clear plan, otherwise I'm blocking all trivial PR's.

**Pull request closed without merging**
