### PR TITLE
Fixed step count by looking for _devtools files first

### PR DESCRIPTION
**Pull request by alexandrul**
Fixes https://github.com/WPO-Foundation/webpagetest/issues/1088

### CODE REVIEW

**Comment by alexandrul** [comment]
I'm not sure if there is a case where there could be more `_devtools_requests` files than `_devtools` ones.

If there is no such thing, the `_devtools_requests` count could be deleted.

If there is, I can update this PR to get the max from both file counts.

**Comment by pmeenan** [comment]
I'll take a look at this closer in the morning but I think the best approach would be to extract the step names from any files that have them (there are 2 common patterns) and just use the highest step name found regardless of file type.  That way if anything is missing from the middle it will all still display correctly.

**Comment by alexandrul** [comment]
Agree, it's a much better solution.

I would propose to discard the `cached` part in the regex, since both First View and Repeat View should have the same step count. This way, if max step number would be 5 in First View and 4 in Repeat View, the reported step count should be 5 in both cases.

**Comment by pmeenan** [comment]
Pushed the fix [here](https://github.com/WPO-Foundation/webpagetest/commit/a940336c2bfe85dd1e43fa459f45567f5239f7ee).  In theory cached/FV could have different number of steps if the conditional commands are used (with the older agent that supported them).  If it becomes a display problem we should probably fix it where it is displayed.

**Comment by alexandrul** [comment]
Thank you very much.

**Pull request closed without merging**
