### PR TITLE
Remove Bulk file uploads in favor of File Reader

### PR DESCRIPTION
**Pull request by stoyan**
* consistent with the other textareas where we allow them to be populated from a text file
* client side, no uploads

### CODE REVIEW

**Comment by stoyan** [comment]
@pmeenan, wdyt? It should not affect API call, correct?

**Comment by stoyan** [comment]
## before
Screenshot 2023-01-10 at 4 59 50 PM

## after
Screenshot 2023-01-10 at 4 59 14 PM

**Comment by pmeenan** [comment]
Should be ok.  Technically, it affects the api since runtest.php no longer handles bulkfile but I'd be shocked if anyone used the API for running bulk testing that way (and even more shocked if they used bulkfile).  If you're using the API already, odds are you are sending each URL as a separate API call.

**Comment by pmeenan** [comment]
If you want to be particularly safe, remove the UI side of things but leave the handling in runtest.php alone.

**Comment by stoyan** [comment]
>  If you're using the API already, odds are you are sending each URL as a separate API call.

yeah, or use the `bulkurl`

Also the API docs do not contain the word "bulk" :)

**Comment by pmeenan** [comment]
The one I was less sure about was the bulk tester google doc that Andy put together but it looks like it also uses the API for individual URLs: https://github.com/WebPageTest/WebPageTest-Bulk-Tester/blob/master/webpagetest.gs

I'd go ahead and remove it.

**Pull request merged**
