### PR TITLE
Added XLabs Security WAF

### PR DESCRIPTION
**Pull request by xlabssecurity**

### CODE REVIEW

**Comment by pmeenan** [comment]
Do you have an edge map or some sample sites that are on the WAF so I can check to make sure it geo-distributes the traffic?  The RTT from the US to the www.xlabs.com.br domain is ~128ms for example which doesn't look very CDN-like.

**Comment by xlabssecurity** [comment]
Hello Patrick,
We are working to raise the PoPs of our CDN still this year, we are in the final phase of adapting our WAF platform in SaaS with the addition of CDN.
Soon we will be with PoP's in the USA.

**Comment by pmeenan** [comment]
USA isn't strictly necessary but geo distribution for performance is depending on the markets you target.  Feel free to re-open once you are ready and I can add it.

**Comment by xlabssecurity** [comment]
Hello Patrick
Ping the www.internacional.com.br please.

Thanks.

**Comment by xlabssecurity** [comment]
Hello @pmeenan 
image

**Comment by pmeenan** [comment]
The wptdriver agent is deprecated now and most agents have been migrated to wptagent.  I [just added](https://github.com/WPO-Foundation/wptagent/commit/ad22073b3effb3c28f1c5dedd3fe010f6f9bd7c1) the detection there.

**Pull request closed without merging**
