### PR TITLE
1536 - offer checkbox to preserve UA when ttfb is seemingly skewed for bots

### PR DESCRIPTION
**Pull request by scottjehl**
Not yet ready to merge!

First pass on messaging for a checkbox that we'll offer when a result has slow ttfb and  seems to be skewed for bots. 

Live example of this message showing in a slow result: 
image
image

### CODE REVIEW

**Comment by scottjehl** [comment]
Note: there's a todo in there noting that we (seemingly at least) need a public function to grab the median ttfb or other metric. There are similar functions to grab the median run number but not the data, from this particular file's access at least. I am still looking though! :)

**Comment by tkadlec** [comment]
@scottjehl What do you think about only showing this message if all the test runs have a TTFB over that threshold to avoid a situation where one load really is that much slower?

If we did that, we'd need to loop through each run to get the TTFB for each OR write a function that can does that when provided with a particular metric.

**Comment by scottjehl** [comment]
Oh, yeah that's even better. Good idea, thanks. I'll aim to make a function that returns an array from the runs of a particular passed metric.

**Review by tkadlec — APPROVED** [review]
Code comments? What is this new sorcery? ;)

**Review by tkadlec — APPROVED** [review]
This looks great!

**Pull request merged**
