### PR TITLE
Support for S3 path-style URLs

### PR DESCRIPTION
**Pull request by Verkurkie**
- added config key 'archive_s3_urlstyle' to sesttings.ini.sample
- updated www/archive.inc to pass the new key to S3 class
- updated www/lib/S3.php to pass new key to S3Request class

Tested on local install:
- www/cli/archive.php successfully archived results to internal S3-based system
- webpagetest GUI successfully retrieved archived results

### CODE REVIEW

**Comment by pmeenan** [comment]
Looks like there are still a bunch of conflicts with master and picking up a bunch of other changes.  If you can get it to merge cleanly and it doesn't break any existing archiving I'm happy to take another look.

**Comment by Verkurkie** [comment]
Hey Pat,

Not sure I did everything right but it looks like my fork is OK now and merge conflicts have been resolved. Let me know if I screwed anything up!

The diffs of www/archive.inc and www/settings/settings.ini.sample (https://github.com/WPO-Foundation/webpagetest/compare/master...Verkurkie:master) look different because I had to recreate those two files to resolve merge conflicts.

This commit: https://github.com/WPO-Foundation/webpagetest/pull/843/commits/24b0cf532f36e5121bc70b3979f783180947dc18 holds the original changes …

Thanks for looking into it!
-marcel

**Comment by pmeenan** [comment]
Mostly good.  Looks like 2 blocks of sample settings were dropped.  It might also be good to add a comment to the s3 section for what a path-style setting would look like.

**Comment by Verkurkie** [comment]
updated settings.ini.sample:

-          two missing blocks were added back

-          expanded the s3 “url style” section with some examples of what vhost/path style URLs look like

See commit d6f1874<https://github.com/WPO-Foundation/webpagetest/pull/843/commits/d6f1874fd928a07b33a799509b316ff4688ad1a7>

**Pull request merged**
